server:
  port: 9094

spring:
  application:
    name: notification-service
  config:
    import: "optional:file:.env[.properties]"
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true                # Kimlik doğrulamasını zorunlu kılar
          starttls:
            enable: true           # BU SATIR KRİTİK: Bağlantıyı TLS ile şifreler
            required: true         # Şifreleme olmazsa gönderme der
          connectiontimeout: 5000  # Bağlantı için çok bekleme
          timeout: 5000
          writetimeout: 5000

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}



auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    issuer: ${JWT_ISSUER}