server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: "optional:file:.env[.properties]"
  cloud:
    gateway:
      routes:
        # AUTH SERVICE YÖNLENDİRMESİ
        - id: auth-service
          uri: http://localhost:9090 # Arka plandaki gerçek servis adresi
          predicates:
            - Path=/dev/v1/auth/** # Bu URL ile gelenleri yakala

        # USER SERVICE YÖNLENDİRMESİ
        - id: user-service
          uri: http://localhost:9091
          predicates:
            - Path=/dev/v1/user/** # Senin controller'daki path yapına göre

        # COMPLAINT SERVICE YÖNLENDİRMESİ
        - id: complaint-service
          uri: http://localhost:9093
          predicates:
            - Path=/dev/v1/complaints/**

        # NOTIFICATION SERVICE YÖNLENDİRMESİ (Opsiyonel, genelde dışarıya açılmaz)
        - id: notification-service
          uri: http://localhost:9094
          predicates:
            - Path=/dev/v1/notifications/**

auth:
  jwt:
    secret-key: uulyjNTBUNcsH5iKUTB6iar+7FCyQucWjgAuCHP9C1k=
    issuer: EnesIncekara