server:
  port: 9091

spring:

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/user_db?authSource=admin

  config:
    import: "optional:file:.env[.properties]"

  application:
    name: user-service


management:
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: "W3C"
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  # Spring Boot 3'ün bu verileri loglara enjekte etmesini sağlar
  register-proxy: true
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    issuer: ${JWT_ISSUER}